{% set name = "xplugin" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/xplugin/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 11e2325bceb495475b7126f0606e1ada077d603248cc26788ab6616bc3e7587f

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/xplugin  # [unix]
    - test -f ${PREFIX}/include/xplugin/xfactory.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplugin/xpluginConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplugin/xpluginTargets.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xplugin/xplugin_add_xplugin.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xplugin\xfactory.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xplugin\xpluginConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xplugin\xpluginTargets.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xplugin\xplugin_add_xplugin.cmake (exit 1)  # [win]

about:
  home: https://github.com/QuantStack/xplugin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Generic C++ plugin system
  description: Generic header only C++ plugin system without any depenencies
  doc_url: https://github.com/QuantStack/xplugin
  dev_url: https://github.com/QuantStack/xplugin

extra:
  recipe-maintainers:
    - DerThorsten
    - JohanMabille
